language: php
services: mysql

php:
  - 7.4

cache:
  directories:
    - vendor

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --dry-run -v
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
