language: php
services: mysql

php:
  - 7.4

cache:
  directories:
    - vendor

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test

matrix:
  fast_finish: true
