language: php
services: mysql

php:
  - 8.0
  - 8.1

cache:
  directories:
    - vendor

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test

matrix:
  fast_finish: true
